spring:
  datasource:
    username: root
    password: mypassword
    url: jdbc:mysql://134.175.54.171:3306/shenyou?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:org/lanqiao/mapper/*.xml
  type-aliases-package: org.lanqiao.entity

#showSql
logging:
  level:
    org:
      lanqiao:
        mapper : debug
